version: '3.8'

services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - POSTGRES_DB=$YOUR_DB_NAME
    ports:
      - "$POSTGRES_DOCKER_PORT:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app_bmps_service:
    image: 'agusramdan/app_bmps_service:latest'
    build:
      context: .
    container_name: app_bmps_service
    depends_on:
      - db_postgres
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/$YOUR_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$YOUR_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$YOUR_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=$PROFILES_ACTIVE
      - KEYCLOAK_RESOURCE=${APP_BPMS_KC_RESOURCE:-bpms}
      - KEYCLOAK_REALM=${APP_BPMS_KC_REALM:-demo}
      - KEYCLOAK_AUTH_SERVER_URL=${APP_BPMS_KC_AUTH_SERVER_URL:-https://merahputih-id.tech:9443/auth}

    ports:
      - "$APP_BMPS_DOCKER_PORT:8080"



volumes:
  pgdata:
