version: '3.8'

services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - POSTGRES_DB=$YOUR_DB_NAME
    ports:
      - "$POSTGRES_DOCKER_PORT:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app_bmps_service:
    image: 'agusramdan/app_bmps_service:latest'
    build:
      context: .
    container_name: app_bmps_service
    depends_on:
      - db_postgres
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/$YOUR_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$YOUR_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$YOUR_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=$PROFILES_ACTIVE

    ports:
      - "$APP_BMPS_DOCKER_PORT:8080"

  keycloak-server:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"

volumes:
  pgdata:
