version: '3.8'

services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - POSTGRES_DB=$YOUR_DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  authorization-server:
    image: 'agusramdan/authorization-server:latest'
    build:
      context: .
    container_name: authorization-server
    depends_on:
      - db_postgres
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS="-Xms516M -Xmx516M"

  app_bmps_service:
    image: 'agusramdan/app_bmps_service:latest'
    build:
      context: .
    container_name: app_bmps_service
    depends_on:
      - db_postgres
      - zipkin
      - logstash
    environment:
      - SPRING_PROFILES_ACTIVE=$PROFILES_ACTIVE
      - JAVA_OPTS="-Xms516M -Xmx516M"
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/$YOUR_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$YOUR_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$YOUR_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KEYCLOAK_RESOURCE=${APP_BPMS_KC_RESOURCE:-bpms}
      - KEYCLOAK_REALM=${APP_BPMS_KC_REALM:-demo}
      - KEYCLOAK_AUTH_SERVER_URL=${APP_BPMS_KC_AUTH_SERVER_URL:-https://merahputih-id.tech:9443/auth}
    ports:
      - "8080:8080"

  api-cdm-core-service:
    image: 'agusramdan/api-cdm_core-service:latest'
    build:
      context: .
    container_name: api-cdm-core-service
    depends_on:
      - zipkin
      - logstash
    environment:
      - SPRING_PROFILES_ACTIVE=dev,zipkin
      - JAVA_OPTS="-Xms516M -Xmx516M"
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/$YOUR_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$YOUR_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$YOUR_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8080"

  api-cdm-service:
    image: 'agusramdan/api-cdm-service:latest'
    build:
      context: .
    container_name: api-cdm-service
    depends_on:
      - app_bmps_service
      - api-cdm-core-service
      - zipkin
      - logstash
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://merahputih-id.tech:9000
      - SPRING_PROFILES_ACTIVE=oauth2,zipkin
      - JAVA_OPTS="-Xms516M -Xmx516M"
    ports:
      - "8084:8080"

volumes:
  pgdata:
