version: '3.8'

services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    environment:
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - POSTGRES_DB=$YOUR_DB_NAME
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "5000:5000"
      - "9600:9600"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  authorization-server:
    image: 'agusramdan/authorization-server:latest'
    build:
      context: .
    container_name: authorization-server
    depends_on:
      - db_postgres
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS="-Xms256M -Xmx256M"

  api-cdt-core-master-service:
    image: 'agusramdan/api-cdt-core-master-service:dev'
    build:
      context: .
    container_name: api-cdt-core-master-service
    depends_on:
      - zipkin
      - logstash
    environment:
      - SPRING_PROFILES_ACTIVE=zipkin
      - JAVA_OPTS="-Xms256M -Xmx256M"
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/$YOUR_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$YOUR_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$YOUR_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8080"

  api-cdt-core-trx-service:
    image: 'agusramdan/api-cdt-core-trx-service:dev'
    container_name: api-cdt-core-trx-service
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - SPRING_PROFILES_ACTIVE=zipkin
      - JAVA_OPTS="-Xms256M -Xmx256M"
      - POSTGRES_USER=$YOUR_USERNAME
      - POSTGRES_PASSWORD=$YOUR_PASSWORD
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres:5432/$YOUR_DB_NAME
      - SPRING_DATASOURCE_USERNAME=$YOUR_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$YOUR_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8080"

  api-cdm-service:
    image: 'agusramdan/api-cdm-service:latest'
    build:
      context: .
    container_name: api-cdm-service
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - api-cdm-core-service
      - zipkin
      - logstash
    environment:
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://merahputih-id.tech:9000
      - SPRING_PROFILES_ACTIVE=oauth2,zipkin
      - JAVA_OPTS="-Xms256M -Xmx256M"
    ports:
      - "8091:8080"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --schedule "0 * * * *" --label-enable

volumes:
  pgdata:
