---
#Keycloak authorization properties
keycloak:
  enabled: true
  realm: demo
  resource: ${spring.application.name}
  auth-server-url: https://merahputih-id.tech:9443/auth
  ssl-required: external
  use-resource-role-mappings: true

app:
  keycloak:
    login:
      url: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
    grant-type: password
    client-id: ${keycloak.resource}
    client-secret: 53905103-24fd-49ca-b0b7-b08ff0ce3355


spring:
  main:
    allow-circular-references: true