package com.agus.ramdan.bmps.machine.dto;

import com.agus.ramdan.bmps.machine.domain.TrxDepositMachine;
import com.agus.ramdan.bmps.machine.domain.TrxDepositMachineDenomination;
import com.agus.ramdan.bmps.machine.dto.*;
import org.mapstruct.*;

@Mapper(unmappedTargetPolicy = ReportingPolicy.IGNORE, componentModel = "spring")
public interface TrxDepositMachineMapper {
    TrxDepositMachine trxDepositMachineDtoToTrxDepositMachine(TrxDepositMachineDto trxDepositMachineDto);

    TrxDepositMachineDto trxDepositMachineToTrxDepositMachineDto(TrxDepositMachine trxDepositMachine);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    TrxDepositMachine updateTrxDepositMachineFromTrxDepositMachineDto(TrxDepositMachineDto trxDepositMachineDto, @MappingTarget TrxDepositMachine trxDepositMachine);

    TrxDepositMachineDenomination trxDepositMachineDenominationDtoToTrxDepositMachineDenomination(TrxDepositMachineDenominationDto trxDepositMachineDenominationDto);

    TrxDepositMachineDenominationDto trxDepositMachineDenominationToTrxDepositMachineDenominationDto(TrxDepositMachineDenomination trxDepositMachineDenomination);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    TrxDepositMachineDenomination updateTrxDepositMachineDenominationFromTrxDepositMachineDenominationDto(TrxDepositMachineDenominationDto trxDepositMachineDenominationDto, @MappingTarget TrxDepositMachineDenomination trxDepositMachineDenomination);

    TrxDepositMachineDenomination trxDepositMachineDenominationRequestToTrxDepositMachineDenomination(TrxDepositMachineDenominationRequest trxDepositMachineDenominationRequest);

    TrxDepositMachineDenominationRequest trxDepositMachineDenominationToTrxDepositMachineDenominationRequest(TrxDepositMachineDenomination trxDepositMachineDenomination);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    TrxDepositMachineDenomination updateTrxDepositMachineDenominationFromTrxDepositMachineDenominationRequest(TrxDepositMachineDenominationRequest trxDepositMachineDenominationRequest, @MappingTarget TrxDepositMachineDenomination trxDepositMachineDenomination);

    TrxDepositMachine trxDepositMachineRequestToTrxDepositMachine(TrxDepositMachineRequest trxDepositMachineRequest);

    TrxDepositMachineRequest trxDepositMachineToTrxDepositMachineRequest(TrxDepositMachine trxDepositMachine);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    TrxDepositMachine updateTrxDepositMachineFromTrxDepositMachineRequest(TrxDepositMachineRequest trxDepositMachineRequest, @MappingTarget TrxDepositMachine trxDepositMachine);

    TrxDepositMachine trxDepositMachineResponseToTrxDepositMachine(TrxDepositMachineResponse trxDepositMachineResponse);

    TrxDepositMachineResponse trxDepositMachineToTrxDepositMachineResponse(TrxDepositMachine trxDepositMachine);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    TrxDepositMachine updateTrxDepositMachineFromTrxDepositMachineResponse(TrxDepositMachineResponse trxDepositMachineResponse, @MappingTarget TrxDepositMachine trxDepositMachine);
}
